[toolchain]
channel = "nightly"
components = [
  "rust-src",
  "rust-analyzer",
  "rustc-codegen-cranelift",
  "miri",
  "llvm-tools",
  "rust-docs-json",
]
targets = [
  "aarch64-unknown-linux-gnu"
]
profile = "default"

