{
  inputs,
  self,
  ...
}:
inputs.nixpkgs.lib.nixosSystem {
  system = "x86_64-linux";
  specialArgs = {inherit inputs;};
  modules = let
    user = "bryce";
    host = "starboard";
    headless = false;
  in
    [
      ({
        inputs,
        pkgs,
        config,
        lib,
        ...
      }: {
        system = import ../../modules/nixos/system.nix {inherit self;};
        time = import ../../modules/nixos/time.nix;
        boot = import ../../modules/nixos/boot.nix;
        environment = import ../../modules/common/environment.nix {inherit headless host pkgs inputs;};
        nixpkgs = let platform = "x86_64-linux"; in import ../../modules/common/nixpkgs.nix {inherit platform self;};
        users.users = import ../../modules/nixos/user.nix {inherit user pkgs;};
        networking = import ../../modules/nixos/networking.nix;
        zramSwap.enable = true;
        services = {
          clamav.daemon.enable = true;
          fail2ban.enable = true;
          fstrim.enable = true;
          fwupd.enable = true;
          libinput.enable = true;
          ollama.enable = true;
          power-profiles-daemon.enable = true;
          tumbler.enable = true;
          colord.enable = true;
          dbus = import ../../modules/nixos/dbus.nix;
          # dnscypt-proxy2 = import ../../modules/nixos/dnscrypt-proxy2.nix;
          fprintd = import ../../modules/nixos/fprintd.nix {inherit pkgs;};
          greetd = import ../../modules/nixos/display-manager.nix {inherit pkgs;};
          keyd = import ../../modules/nixos/keyd.nix;
          openssh = import ../../modules/nixos/openssh.nix;
          pipewire = import ../../modules/nixos/pipewire.nix;
          udev = import ../../modules/nixos/udev.nix;
          xserver = import ../../modules/nixos/xserver.nix;
        };
        console.useXkbConfig = true;
        security = import ../../modules/nixos/security.nix {inherit pkgs;};
        nix = import ../../modules/common/nix-settings.nix {inherit inputs;};
        programs = {
          fish.enable = true;
          light.enable = true;
          dconf.enable = true;
          thunar.enable = true;
          hyprland = import ../../modules/nixos/hyprland.nix {inherit inputs pkgs;};
        };
        hardware = import ../../modules/nixos/framework-hardware.nix {inherit pkgs config;};
        systemd.services.dnscrypt-proxy2.serviceConfig.StateDirectory = "dnscrypt-proxy";
        i18n = import ../../modules/nixos/locale.nix;
        home-manager = {
          useGlobalPkgs = true;
          backupFileExtension = "bak";
          users = {
            ${user} = import ../../modules/home/users/user.nix {inherit pkgs user host lib inputs;};
          };
        };
      })
    ]
    ++ [
      inputs.hardware.nixosModules.framework-13-7040-amd
      inputs.home-manager.nixosModules.home-manager
      inputs.nix-index.nixosModules.nix-index
      inputs.lix.nixosModules.default
      ./hardware-configuration.nix # This is automatically generated by nixos.
    ];
}
